//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BigIsLoserModel", "FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Post", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BigISLoser.Repositories.WeightMsg_Post), "WeightMsg_Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BigISLoser.Repositories.WeightMsg_Comment), true)]
[assembly: EdmRelationshipAttribute("BigIsLoserModel", "FK_WeightMsg_Post_WeightUsers", "WeightUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BigISLoser.Repositories.WeightUser), "WeightMsg_Post", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BigISLoser.Repositories.WeightMsg_Post), true)]
[assembly: EdmRelationshipAttribute("BigIsLoserModel", "FK_WeightMsg_Comment_WeightUsers", "WeightUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BigISLoser.Repositories.WeightUser), "WeightMsg_Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BigISLoser.Repositories.WeightMsg_Comment), true)]
[assembly: EdmRelationshipAttribute("BigIsLoserModel", "FK_WeightCheckIns_WeightUsers", "WeightUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BigISLoser.Repositories.WeightUser), "WeightCheckIn", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BigISLoser.Repositories.WeightCheckIn), true)]

#endregion

namespace BigISLoser.Repositories
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WeightMsg_Comment> WeightMsg_Comment
        {
            get
            {
                if ((_WeightMsg_Comment == null))
                {
                    _WeightMsg_Comment = base.CreateObjectSet<WeightMsg_Comment>("WeightMsg_Comment");
                }
                return _WeightMsg_Comment;
            }
        }
        private ObjectSet<WeightMsg_Comment> _WeightMsg_Comment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WeightMsg_Post> WeightMsg_Post
        {
            get
            {
                if ((_WeightMsg_Post == null))
                {
                    _WeightMsg_Post = base.CreateObjectSet<WeightMsg_Post>("WeightMsg_Post");
                }
                return _WeightMsg_Post;
            }
        }
        private ObjectSet<WeightMsg_Post> _WeightMsg_Post;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WeightUser> WeightUsers
        {
            get
            {
                if ((_WeightUsers == null))
                {
                    _WeightUsers = base.CreateObjectSet<WeightUser>("WeightUsers");
                }
                return _WeightUsers;
            }
        }
        private ObjectSet<WeightUser> _WeightUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WeightCheckIn> WeightCheckIns
        {
            get
            {
                if ((_WeightCheckIns == null))
                {
                    _WeightCheckIns = base.CreateObjectSet<WeightCheckIn>("WeightCheckIns");
                }
                return _WeightCheckIns;
            }
        }
        private ObjectSet<WeightCheckIn> _WeightCheckIns;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WeightMsg_Comment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeightMsg_Comment(WeightMsg_Comment weightMsg_Comment)
        {
            base.AddObject("WeightMsg_Comment", weightMsg_Comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WeightMsg_Post EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeightMsg_Post(WeightMsg_Post weightMsg_Post)
        {
            base.AddObject("WeightMsg_Post", weightMsg_Post);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WeightUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeightUsers(WeightUser weightUser)
        {
            base.AddObject("WeightUsers", weightUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WeightCheckIns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeightCheckIns(WeightCheckIn weightCheckIn)
        {
            base.AddObject("WeightCheckIns", weightCheckIn);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BigIsLoserModel", Name="WeightCheckIn")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WeightCheckIn : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WeightCheckIn object.
        /// </summary>
        /// <param name="checkInID">Initial value of the CheckInID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="checkInDate">Initial value of the CheckInDate property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        public static WeightCheckIn CreateWeightCheckIn(global::System.Int32 checkInID, global::System.Int32 userID, global::System.DateTime checkInDate, global::System.Int32 weight)
        {
            WeightCheckIn weightCheckIn = new WeightCheckIn();
            weightCheckIn.CheckInID = checkInID;
            weightCheckIn.UserID = userID;
            weightCheckIn.CheckInDate = checkInDate;
            weightCheckIn.Weight = weight;
            return weightCheckIn;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CheckInID
        {
            get
            {
                return _CheckInID;
            }
            set
            {
                if (_CheckInID != value)
                {
                    OnCheckInIDChanging(value);
                    ReportPropertyChanging("CheckInID");
                    _CheckInID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CheckInID");
                    OnCheckInIDChanged();
                }
            }
        }
        private global::System.Int32 _CheckInID;
        partial void OnCheckInIDChanging(global::System.Int32 value);
        partial void OnCheckInIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CheckInDate
        {
            get
            {
                return _CheckInDate;
            }
            set
            {
                OnCheckInDateChanging(value);
                ReportPropertyChanging("CheckInDate");
                _CheckInDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheckInDate");
                OnCheckInDateChanged();
            }
        }
        private global::System.DateTime _CheckInDate;
        partial void OnCheckInDateChanging(global::System.DateTime value);
        partial void OnCheckInDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Int32 _Weight;
        partial void OnWeightChanging(global::System.Int32 value);
        partial void OnWeightChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightCheckIns_WeightUsers", "WeightUser")]
        public WeightUser WeightUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightCheckIns_WeightUsers", "WeightUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightCheckIns_WeightUsers", "WeightUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WeightUser> WeightUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightCheckIns_WeightUsers", "WeightUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightCheckIns_WeightUsers", "WeightUser", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BigIsLoserModel", Name="WeightMsg_Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WeightMsg_Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WeightMsg_Comment object.
        /// </summary>
        /// <param name="comment_ID">Initial value of the Comment_ID property.</param>
        /// <param name="post_ID">Initial value of the Post_ID property.</param>
        /// <param name="comment_DateTime">Initial value of the Comment_DateTime property.</param>
        /// <param name="comment_HTML">Initial value of the Comment_HTML property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static WeightMsg_Comment CreateWeightMsg_Comment(global::System.Int32 comment_ID, global::System.Int32 post_ID, global::System.DateTime comment_DateTime, global::System.String comment_HTML, global::System.Int32 userID)
        {
            WeightMsg_Comment weightMsg_Comment = new WeightMsg_Comment();
            weightMsg_Comment.Comment_ID = comment_ID;
            weightMsg_Comment.Post_ID = post_ID;
            weightMsg_Comment.Comment_DateTime = comment_DateTime;
            weightMsg_Comment.Comment_HTML = comment_HTML;
            weightMsg_Comment.UserID = userID;
            return weightMsg_Comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Comment_ID
        {
            get
            {
                return _Comment_ID;
            }
            set
            {
                if (_Comment_ID != value)
                {
                    OnComment_IDChanging(value);
                    ReportPropertyChanging("Comment_ID");
                    _Comment_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Comment_ID");
                    OnComment_IDChanged();
                }
            }
        }
        private global::System.Int32 _Comment_ID;
        partial void OnComment_IDChanging(global::System.Int32 value);
        partial void OnComment_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Post_ID
        {
            get
            {
                return _Post_ID;
            }
            set
            {
                OnPost_IDChanging(value);
                ReportPropertyChanging("Post_ID");
                _Post_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Post_ID");
                OnPost_IDChanged();
            }
        }
        private global::System.Int32 _Post_ID;
        partial void OnPost_IDChanging(global::System.Int32 value);
        partial void OnPost_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Comment_DateTime
        {
            get
            {
                return _Comment_DateTime;
            }
            set
            {
                OnComment_DateTimeChanging(value);
                ReportPropertyChanging("Comment_DateTime");
                _Comment_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Comment_DateTime");
                OnComment_DateTimeChanged();
            }
        }
        private global::System.DateTime _Comment_DateTime;
        partial void OnComment_DateTimeChanging(global::System.DateTime value);
        partial void OnComment_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comment_HTML
        {
            get
            {
                return _Comment_HTML;
            }
            set
            {
                OnComment_HTMLChanging(value);
                ReportPropertyChanging("Comment_HTML");
                _Comment_HTML = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comment_HTML");
                OnComment_HTMLChanged();
            }
        }
        private global::System.String _Comment_HTML;
        partial void OnComment_HTMLChanging(global::System.String value);
        partial void OnComment_HTMLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Post")]
        public WeightMsg_Post WeightMsg_Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightMsg_Post>("BigIsLoserModel.FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Post").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightMsg_Post>("BigIsLoserModel.FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Post").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WeightMsg_Post> WeightMsg_PostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightMsg_Post>("BigIsLoserModel.FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WeightMsg_Post>("BigIsLoserModel.FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Post", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightMsg_Comment_WeightUsers", "WeightUser")]
        public WeightUser WeightUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Comment_WeightUsers", "WeightUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Comment_WeightUsers", "WeightUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WeightUser> WeightUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Comment_WeightUsers", "WeightUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Comment_WeightUsers", "WeightUser", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BigIsLoserModel", Name="WeightMsg_Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WeightMsg_Post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WeightMsg_Post object.
        /// </summary>
        /// <param name="post_ID">Initial value of the Post_ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="post_Content">Initial value of the Post_Content property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="dateModified">Initial value of the DateModified property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static WeightMsg_Post CreateWeightMsg_Post(global::System.Int32 post_ID, global::System.String title, global::System.String post_Content, global::System.DateTime dateCreated, global::System.DateTime dateModified, global::System.Int32 userID)
        {
            WeightMsg_Post weightMsg_Post = new WeightMsg_Post();
            weightMsg_Post.Post_ID = post_ID;
            weightMsg_Post.Title = title;
            weightMsg_Post.Post_Content = post_Content;
            weightMsg_Post.DateCreated = dateCreated;
            weightMsg_Post.DateModified = dateModified;
            weightMsg_Post.UserID = userID;
            return weightMsg_Post;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Post_ID
        {
            get
            {
                return _Post_ID;
            }
            set
            {
                if (_Post_ID != value)
                {
                    OnPost_IDChanging(value);
                    ReportPropertyChanging("Post_ID");
                    _Post_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Post_ID");
                    OnPost_IDChanged();
                }
            }
        }
        private global::System.Int32 _Post_ID;
        partial void OnPost_IDChanging(global::System.Int32 value);
        partial void OnPost_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Post_Content
        {
            get
            {
                return _Post_Content;
            }
            set
            {
                OnPost_ContentChanging(value);
                ReportPropertyChanging("Post_Content");
                _Post_Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Post_Content");
                OnPost_ContentChanged();
            }
        }
        private global::System.String _Post_Content;
        partial void OnPost_ContentChanging(global::System.String value);
        partial void OnPost_ContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Comment")]
        public EntityCollection<WeightMsg_Comment> WeightMsg_Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WeightMsg_Comment>("BigIsLoserModel.FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WeightMsg_Comment>("BigIsLoserModel.FK_WeightMsg_Comment_WeightMsg_Post", "WeightMsg_Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightMsg_Post_WeightUsers", "WeightUser")]
        public WeightUser WeightUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Post_WeightUsers", "WeightUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Post_WeightUsers", "WeightUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WeightUser> WeightUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Post_WeightUsers", "WeightUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WeightUser>("BigIsLoserModel.FK_WeightMsg_Post_WeightUsers", "WeightUser", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BigIsLoserModel", Name="WeightUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WeightUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WeightUser object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="displayName">Initial value of the DisplayName property.</param>
        /// <param name="pW">Initial value of the PW property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="signUpDateTime">Initial value of the SignUpDateTime property.</param>
        /// <param name="admin">Initial value of the Admin property.</param>
        /// <param name="paid">Initial value of the Paid property.</param>
        public static WeightUser CreateWeightUser(global::System.Int32 userID, global::System.Boolean displayName, global::System.String pW, global::System.Boolean active, global::System.DateTime signUpDateTime, global::System.Boolean admin, global::System.Decimal paid)
        {
            WeightUser weightUser = new WeightUser();
            weightUser.UserID = userID;
            weightUser.DisplayName = displayName;
            weightUser.PW = pW;
            weightUser.Active = active;
            weightUser.SignUpDateTime = signUpDateTime;
            weightUser.Admin = admin;
            weightUser.Paid = paid;
            return weightUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.Boolean _DisplayName;
        partial void OnDisplayNameChanging(global::System.Boolean value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PW
        {
            get
            {
                return _PW;
            }
            set
            {
                OnPWChanging(value);
                ReportPropertyChanging("PW");
                _PW = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PW");
                OnPWChanged();
            }
        }
        private global::System.String _PW;
        partial void OnPWChanging(global::System.String value);
        partial void OnPWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SignUpDateTime
        {
            get
            {
                return _SignUpDateTime;
            }
            set
            {
                OnSignUpDateTimeChanging(value);
                ReportPropertyChanging("SignUpDateTime");
                _SignUpDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SignUpDateTime");
                OnSignUpDateTimeChanged();
            }
        }
        private global::System.DateTime _SignUpDateTime;
        partial void OnSignUpDateTimeChanging(global::System.DateTime value);
        partial void OnSignUpDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StartWeight
        {
            get
            {
                return _StartWeight;
            }
            set
            {
                OnStartWeightChanging(value);
                ReportPropertyChanging("StartWeight");
                _StartWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartWeight");
                OnStartWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _StartWeight;
        partial void OnStartWeightChanging(Nullable<global::System.Int32> value);
        partial void OnStartWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GoalWeight
        {
            get
            {
                return _GoalWeight;
            }
            set
            {
                OnGoalWeightChanging(value);
                ReportPropertyChanging("GoalWeight");
                _GoalWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GoalWeight");
                OnGoalWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _GoalWeight;
        partial void OnGoalWeightChanging(Nullable<global::System.Int32> value);
        partial void OnGoalWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EndWeight
        {
            get
            {
                return _EndWeight;
            }
            set
            {
                OnEndWeightChanging(value);
                ReportPropertyChanging("EndWeight");
                _EndWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndWeight");
                OnEndWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _EndWeight;
        partial void OnEndWeightChanging(Nullable<global::System.Int32> value);
        partial void OnEndWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Admin
        {
            get
            {
                return _Admin;
            }
            set
            {
                OnAdminChanging(value);
                ReportPropertyChanging("Admin");
                _Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Admin");
                OnAdminChanged();
            }
        }
        private global::System.Boolean _Admin;
        partial void OnAdminChanging(global::System.Boolean value);
        partial void OnAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Paid
        {
            get
            {
                return _Paid;
            }
            set
            {
                OnPaidChanging(value);
                ReportPropertyChanging("Paid");
                _Paid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Paid");
                OnPaidChanged();
            }
        }
        private global::System.Decimal _Paid;
        partial void OnPaidChanging(global::System.Decimal value);
        partial void OnPaidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightMsg_Post_WeightUsers", "WeightMsg_Post")]
        public EntityCollection<WeightMsg_Post> WeightMsg_Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WeightMsg_Post>("BigIsLoserModel.FK_WeightMsg_Post_WeightUsers", "WeightMsg_Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WeightMsg_Post>("BigIsLoserModel.FK_WeightMsg_Post_WeightUsers", "WeightMsg_Post", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightMsg_Comment_WeightUsers", "WeightMsg_Comment")]
        public EntityCollection<WeightMsg_Comment> WeightMsg_Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WeightMsg_Comment>("BigIsLoserModel.FK_WeightMsg_Comment_WeightUsers", "WeightMsg_Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WeightMsg_Comment>("BigIsLoserModel.FK_WeightMsg_Comment_WeightUsers", "WeightMsg_Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BigIsLoserModel", "FK_WeightCheckIns_WeightUsers", "WeightCheckIn")]
        public EntityCollection<WeightCheckIn> WeightCheckIns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WeightCheckIn>("BigIsLoserModel.FK_WeightCheckIns_WeightUsers", "WeightCheckIn");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WeightCheckIn>("BigIsLoserModel.FK_WeightCheckIns_WeightUsers", "WeightCheckIn", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
